kcoley/gltf2usd

Source/gltf2usd.py

setting fps throws:
```TypeError: can't multiply sequence by non-int of type 'float'```
This is b/c the fps flag is interpreted as a string by argparse. This changes it to cast it to a `float`.
closes #23, #24

define type of fps arg to get conversion

---

Source/gltf2loader.py

Was getting strange errors about a `.gltf` input file not ending with `.gltf`. Found out I typed the path wrong. Not sure if this should be handled further up the call path, but at least the proper exception is thrown.

gltfloader should warn if file doesn't exist

---

Source/gltf2loader.py

Somehow the `uri` and `buffer_data` vars were overwritten by bb9bdd5, making it impossible to read buffers. :sweat:

P1: put back buffer uri and data in get_data

---

Source/gltf2usd.py

Calling `CreateNewUsdzPackage` with the resolved asset instead of the usdc filename lets the function correctly set the usdc file as the first root file, stripping any relative paths. This also pulls in all of the assets that file references and adjusts their paths in the zipfile.

use resolved asset instead of usdc file to make usdz package

---

Source/gltf2loader.py

I found a model that used `data:application/gltf-buffer` [here], which should really be decoded as an octet-stream. There was also a [model] that curiously used `data:text/plain;base64`, though it was glTF 1.0. 
[here]: https://github.com/KhronosGroup/glTF-Sample-Models/blob/2eaf839717bba9ceb869dc1819af6e1bb98cfd3a/2.0/SimpleMorph/glTF-Embedded/SimpleMorph.gltf#L62
[model]: https://github.com/KhronosGroup/glTF-Sample-Models/blob/2eaf839717bba9ceb869dc1819af6e1bb98cfd3a/1.0/BoxWithoutIndices/glTF-Embedded/BoxWithoutIndices.gltf#L148

decode all base64 data uri, regardless of mime-type

---

Source/gltf2usd.py

*USD does not accept node with digits only names - fixed re.sub.
*when metallic roughness is saved in png (RGBA) the other r g b channels do not get through - it throws an error ->
I added a full split to r g b a replacing the former 'a' only.

I encountered some errors and publishing my solutions - hope it helps

---

CHANGELOG.md
Source/_gltf2usd/gltf2/Animation.py
Source/_gltf2usd/gltf2/Material.py
Source/_gltf2usd/gltf2/Node.py
Source/_gltf2usd/gltf2usdUtils.py
Source/_gltf2usd/usd_material.py
Source/_gltf2usd/version.py
Source/gltf2usd.py
Source/tests/testInitializeGLTFLoader.py

- Fixed issue with node transforms and node animations, where the glTF node transform would get applied on top of its animation, causing incorrect positions.
**Changes:**
- Convert usd file path to absolute path on load  
- Reformatted changelog
- Switched some methods to properties
- Increment version

Fix transforms

---

CHANGELOG.md
Source/_gltf2usd/gltf2/Material.py
Source/_gltf2usd/usd_material.py
Source/_gltf2usd/version.py

- Fixed bug in using specular workflow (https://github.com/kcoley/gltf2usd/pull/92)
**Changes:**
- Added alpha mode to Material (https://github.com/kcoley/gltf2usd/issues/88)
- If opacity is set in glTF, overwrite the alpha to 1 on USD export.  
- Alpha mask is not supported in glTF so a warning is displayed and defaults to alpha blend

added alpha mode

---

CHANGELOG.md
Source/_gltf2usd/gltf2/GLTFImage.py
Source/_gltf2usd/version.py

**Changes:**
- When using alpha opaque, the base color texture is cloned

When using alpha opaque, the base color texture is cloned

---

CHANGELOG.md
Source/_gltf2usd/gltf2/GLTFImage.py
Source/_gltf2usd/version.py

**Changes:**
- If a normal texture has only one channel, the channel is applied to RGB as a new texture

normal texture change

---

CHANGELOG.md
Source/_gltf2usd/gltf2/Mesh.py
Source/_gltf2usd/version.py
Source/gltf2usd.py

**Changes:**
- Set vertex colors for Color4 (vertex color alpha currently not supported)
- Resolves (https://github.com/kcoley/gltf2usd/issues/113)

handle vector4 vertex color

---

CHANGELOG.md
Source/_gltf2usd/gltf2/GLTFImage.py
Source/_gltf2usd/gltf2loader.py
Source/_gltf2usd/version.py
Source/gltf2usd.py

- Fixed a bug where multiple embedded textures within the same buffer were not extracted properly
**Changes:**
- Resolves (https://github.com/kcoley/gltf2usd/issues/125)

multiple embedded textures bug fix

---

CHANGELOG.md
Source/_gltf2usd/gltf2/GLTFImage.py
Source/_gltf2usd/version.py

- Fix for throwing when USD minor version is 19 and path version is 1 [spiderworm](https://github.com/kcoley/gltf2usd/pull/130)
- Fixed bug where texture transform generation would fail on index out of range (https://github.com/kcoley/gltf2usd/issues/131)

fix for texture transform

---

CHANGELOG.md
Source/_gltf2usd/usd_material.py
Source/_gltf2usd/version.py
Source/gltf2usd.py

**Changes:**
- Preserve material names of gltf if present (https://github.com/kcoley/gltf2usd/issues/135)

preserve material name

---

CHANGELOG.md
Source/_gltf2usd/gltf2/Animation.py
Source/_gltf2usd/gltf2/Mesh.py
Source/_gltf2usd/gltf2/Skin.py
Source/_gltf2usd/gltf2loader.py
Source/_gltf2usd/version.py
Source/gltf2usd.py

**Changes:**
- Cache accessor data to help with glTF import optimization (https://github.com/kcoley/gltf2usd/issues/137)
- Adding logging for exporting mesh primitive data, behind the -v flag

cache accessor data

---

CHANGELOG.md
Source/_gltf2usd/gltf2usdUtils.py
Source/_gltf2usd/version.py

**Changes:**
- Update rename regex to include square brackets (https://github.com/kcoley/gltf2usd/issues/144)

update regex to check for square brackets

---

CHANGELOG.md
Source/_gltf2usd/version.py
Source/gltf2usd.py

- Fixed a bug where `TEXCOORD_1` attribute was not being read (https://github.com/kcoley/gltf2usd/issues/149)

support TEXCOORD_1

---

CHANGELOG.md
Source/_gltf2usd/gltf2/Animation.py
Source/_gltf2usd/gltf2/Asset.py
Source/_gltf2usd/gltf2/GLTFImage.py
Source/_gltf2usd/gltf2/Material.py
Source/_gltf2usd/gltf2/Mesh.py
Source/_gltf2usd/gltf2/Node.py
Source/_gltf2usd/gltf2/Scene.py
Source/_gltf2usd/gltf2/Skin.py
Source/_gltf2usd/gltf2loader.py
Source/_gltf2usd/gltf2usdUtils.py
Source/_gltf2usd/gltfUsdMaterialHelper.py
Source/_gltf2usd/usd_material.py
Source/_gltf2usd/version.py
Source/gltf2usd.py

- Fix blend shapes
**Changes:**
- The Usd file generation now happens in a temp directory
- Add `--scale-texture` optional parameter to multiply metallic/roughness factors by textures
- Added creator metadata
- Moved material scope to below root xform
- connect opacity of diffuse texture if alpha blend or mask is used
- Export extras data on nodes and glTF asset

Fix blend shapes

---

README.md

The README included with Apple's prebuilt USD Toolkit seems to specify incorrect paths to have python load the appropriate modules correctly. There is an included USD.command script included with their toolkit though that I thought would be helpful for other developers to know about after I had trouble trying to manually configure the correct paths.

Update README to include hint on USD.command

---

Source/_gltf2usd/gltf2/Animation.py

This is a small fix for the linear interpolation of vectors in the Animation class.
The previous implementation was sampling values from end to start, rather than start to end.
Following is the correct method:
```
float lerp(float v0, float v1, float t) {
return (1 - t) * v0 + t * v1;
}
```

Fix animation linear interpolation
